new aliases, vimrc stuff, new script, fixing batstatus low battery warning bug, bspwm configs

diff --git a/.scripts/anote b/.scripts/anote
--- a/.scripts/anote
+++ b/.scripts/anote
@@ -7,25 +7,61 @@
 #reset for getopts
 OPTIND=1
 
-[ "$NOTES_PATH" ] || NOTES_PATH="$HOME/.notes/"
-# if missing trailing /, add it
-[ "${NOTES_PATH: -1}" == '/' ] || NOTES_PATH="$NOTES_PATH/"
+[ "$NOTES_PATH" ] || NOTES_PATH="$HOME/.notes"
+# Assume there is a trailing /, remove it and add it again.
+# if there is no trailing / it's simply going to add it
+# not so good idea, i know it, but it's the way i could write
+# it in POSIX shell.
+NOTES_PATH="${NOTES_PATH%/}/"
 #create NOTES_PATH directory if it doesn't exists
 [ -d "$NOTES_PATH" ] ||  mkdir $NOTES_PATH
 
 WHICH_NOTES=''
 OPERATION='a'
-TAG=''
+TAG='general'
 NOTE=''
 PATTERN=''
 INVALID=false
+CALCURSE=false
+NOTES_CALCURSE="calcurse"
+
+add_todo_calcurse()
+{
+	# always overwrites the file so that no duplicate notes are added to calcurse
+	echo "BEGIN:VCALENDAR" > $NOTES_PATH.notes$NOTES_CALCURSE
+	echo "VERSION:2.0" >> $NOTES_PATH.notes$NOTES_CALCURSE
+	echo "PRODID:-//calcurse//NONSGML v4.7.0//EN" >> $NOTES_PATH.notes$NOTES_CALCURSE
+
+	if ! [ "$NOTE" = '' ]
+	then
+		echo "BEGIN:VTODO" >> $NOTES_PATH.notes$NOTES_CALCURSE &&
+		echo "PRIORITY:0" >> $NOTES_PATH.notes$NOTES_CALCURSE &&
+		echo "SUMMARY:$NOTE" >> $NOTES_PATH.notes$NOTES_CALCURSE &&
+		echo "END:VTODO" >> $NOTES_PATH.notes$NOTES_CALCURSE
+	fi
+
+	#finish the file
+	echo "END:VCALENDAR" >> $NOTES_PATH.notes$NOTES_CALCURSE
+
+	#import on calcurse
+	calcurse -i $NOTES_PATH.notes$NOTES_CALCURSE
+}
 
 add_note()
 {
-	if ! [ "$NOTE" = '' ]; then
+	if ! [ "$NOTE" = '' ]
+	then
+		#remove any line break if there is any
+		NOTE=$(echo $NOTE | sed s/\\n//g)
+
+		#adds to calcurse if set
+		[ ! "$CALCURSE" = false ] && add_todo_calcurse $NOTE
+
+		#creates file if not exists
 		[ ! -f $NOTES_PATH.notes$TAG ] && touch $NOTES_PATH.notes$TAG
+
 		#gets the last note number from file
-		read NOTE_NUMBER<<<$(awk 'END{print $1}' $NOTES_PATH.notes$TAG | sed s/~//g)
+		NOTE_NUMBER="$(awk 'END{print $1}' $NOTES_PATH.notes$TAG | sed s/~//g)"
 		NOTE_NUMBER=$((NOTE_NUMBER+1))
 		DATE=$(date +%Y-%m-%d)
 		echo "~$NOTE_NUMBER	$DATE	'$NOTE'">>$NOTES_PATH.notes$TAG
@@ -36,14 +72,16 @@ add_note()
 
 list_notes()
 {
-	if [ "$TAG" ]; then
+	if [ "$TAG" ]
+	then
 		WHICH_NOTES=".notes$TAG"
 	else
 		# dmenu prompt to select tag if there are any .notes files
 		[ "$(ls -a $NOTES_PATH | grep ^.notes)" ] && WHICH_NOTES=.notes$(ls -a $NOTES_PATH | grep ^.notes | awk -F " " '{print substr($1,7)}'| dmenu -l 10)
 	fi
 
-	if test -f $NOTES_PATH$WHICH_NOTES; then
+	if test -f $NOTES_PATH$WHICH_NOTES
+	then
 		awk -F "\t" '{print $1". " $3}' $NOTES_PATH$WHICH_NOTES
 	else
 		[ "$TAG" ] && echo "No notes tagged $TAG" || echo "No notes"
@@ -53,9 +91,11 @@ list_notes()
 search_notes()
 {
 	[ "$PATTERN" ] || (echo "Nothing to search for. Exiting" && return)
-	if [ $TAG ]; then
+	if [ $TAG ]
+	then
 		WHICH_NOTES=".notes$TAG"; shift
-		if test -f $NOTES_PATH$WHICH_NOTES; then
+		if test -f $NOTES_PATH$WHICH_NOTES
+		then
 			 grep "$PATTERN" $NOTES_PATH$WHICH_NOTES | awk -F "\t" '{print $1. "\033[34m "$3"\033[0m"}'
 		else
 			echo 'No Notes'
@@ -73,7 +113,8 @@ search_notes()
 
 show_help()
 {
-	echo 'aNote [-t] [SOME TAG] [SOME NOTE]: Adds a note to a specific Tag. If no tag is informed adds to general notes'
+	echo 'aNote [-t] [-c] [SOME TAG] [SOME NOTE]: Adds a note to a specific Tag. If no tag is informed adds to general notes'
+	echo '			  -c: adds note to calcurse todo list'
 	echo 'aNote -l [SOME TAG]:Prompts with a dmenu to select notes file to list notes from
 					-d flag to list general notes'
 	echo 'aNote -s [SOMETHING]: Search for notes with SOMETHING. Date and numbers are valid'
@@ -83,24 +124,22 @@ show_help()
 
 remove_note()
 {
-	if [ "$TAG" ]; then
+	if [ "$TAG" ]
+	then
 		WHICH_NOTES=".notes$TAG";
 	else
 		WHICH_NOTES=.notes$(ls -a $NOTES_PATH | grep ^.notes | awk -F " " '{print substr($1,7)}'| dmenu -l 10)
 	fi
 
-	if test -f "$NOTES_PATH$WHICH_NOTES"; then
-		if [ "$NUMBER" ]; then
-			NOTE="~$NUMBER";
-		else
-			NOTE=$(cat $NOTES_PATH$WHICH_NOTES | sed "s/	/ /g" | dmenu -l 10 | awk -F " " '{print $1}')
-		fi
-
+	if test -f "$NOTES_PATH$WHICH_NOTES"
+	then
+		NOTE=$(cat $NOTES_PATH$WHICH_NOTES | sed "s/	/ /g" | dmenu -l 10 | awk -F " " '{print $1}')
 		if [ "$NOTE" ];then
 			sed '/'"$NOTE"'/d' $NOTES_PATH$WHICH_NOTES > $NOTES_PATH$WHICH_NOTES-aux
 			mv $NOTES_PATH$WHICH_NOTES-aux $NOTES_PATH$WHICH_NOTES
 			ALL_NOTES=$(cat $NOTES_PATH$WHICH_NOTES)
-			if [ ! "$ALL_NOTES" ]; then
+			if [ ! "$ALL_NOTES" ]
+			then
 				rm $NOTES_PATH$WHICH_NOTES
 			fi
 		fi
@@ -110,9 +149,11 @@ remove_note()
 }
 
 
-while getopts ":ds:hlrt:" opt; do
+while getopts ":ds:hlrct:" opt; do
 	#parse arguments before calling any function
 	case $opt in
+		c) CALCURSE=true
+			;;
 		d) TAG='general'
 			;;
 		s) OPERATION='s'
@@ -124,7 +165,6 @@ while getopts ":ds:hlrt:" opt; do
 			TAG="$2"
 			;;
 		r) OPERATION='r'
-			NUMBER="$2"
 			;;
 		t) TAG="$OPTARG"
 			;;
@@ -132,19 +172,18 @@ while getopts ":ds:hlrt:" opt; do
 			show_help
 			;;
 	esac
-	[ "$opt" == ":" ] && echo "Missing argument for $OPTARG" && INVALID=true
+	[ "$opt" = ":" ] && echo "Missing argument for $OPTARG" && INVALID=true
 done
 
 shift $((OPTIND -1))
 # leftover arg is note itself
 NOTE=$@
 
-if [ ! "$INVALID" == "true" ]
+if [ ! "$INVALID" = "true" ]
 then
 	case $OPERATION in
 			# no tag in add means general
-		'a') [ "$TAG" ] || TAG='general'
-			 add_note $NOTE $TAG
+		'a') add_note $NOTE $TAG
 			;;
 		'l') list_notes
 			;;
